### ISSUE TITLE
Fixes to award management

### ISSUE THREAD

**Issue by itamaroryan** [FIRSTIsrael/lems#807]
## Description
Currently, Excellence in Engineering award is always assigned, regardless of if the award is handed out in the division.
Additionally, Optional Awards can be assigned to a team regardless of if the award is handed out in the division.

## TODO
- [x] Don't calculate and assign Excellence in Engineering award if it is not handed out.
- [ ] Don't allow optional awards that are not handed out to be selected in rubric or deliberation.
- [ ] Don't show all corevalues awards in deliberation if not in schema
- [ ] Allow moving to review stage in final deliberation without expecting every award to be assigned (Use schema)
- [ ] Rubrics should only display awards that are in the schema! (Exports too)
- [x] In award schema report, filter out advancement.
- [x] Personal awards don't show in presentation for some reason
- [ ] Teams not in a picklist should be ranked at teams.length. Curently they are ranked 0 which puts them at the lowest average rank and adds them to champion eligibility!!!
