### ISSUE TITLE
FTA User take two

### ISSUE THREAD

**Issue by johnmeshulam** [FIRSTIsrael/lems#837]
## TODO

- [x] Implement new UI
- [x] Add support for stagger in division state
- [x] Highlight buttons in green when: Non-tight (with stagger) OR non registered (call it preferred)
- [x] Staggered editor
- [ ] Solve: After scheduling a rematch the rematch finder does not update until page refresh
- [x] Styling
