### ISSUE TITLE
Notepad Improvements

### ISSUE THREAD

**Issue by johnmeshulam** [FIRSTIsrael/lems#842]
## Description

Styling and UX for notepad

## TODO

- [ ] Drag and drop reordering for notes
- [x] More compact look for notes, maybe 2 column, more likely just move the checkbox to not occupy a new line
- [ ] Popup dialog before deleting note
