### ISSUE TITLE
Scoresheet edge cases

### ISSUE THREAD

**Issue by johnmeshulam** [FIRSTIsrael/lems#847]
## Description

A few low priority scoresheet edge cases to take note of

## TODO

- [ ] When finishing early scoring before the match ends (Run+score, extremely unlikely) the ref is returned to the timer screen.
- [ ] When finishing a scoresheet, there is a split second where the Next button works before the signature pad is loaded and it becomes disabled again.
- [ ] When connected to the same scoresheet from ref and headref, if you fil out the scoresheet on ref and sign, the headref still sees the alert for non-filled scoresheet because nothing triggers the form validation in formik.
