### ISSUE TITLE
Deliberation styling/UX fixes

### ISSUE THREAD

**Issue by johnmeshulam** [FIRSTIsrael/lems#860]
## Description

Some cosmetic improvements to deliberation

## TODO

- [x] Suggested team should be highlighted or with an icon in the table
- [x] Compare feedback is aligned wrongly
- [x] Highlight GP 2/4 in table
- [x] Make anomaly icon colors darker and not transparent
- [x] Sort awards by index in review stage
- [x] Make sure that anomalies outside picklists are displayed in core awards deliberation.
- [x] Make average score purple in room chart
- [x] Pretty sure consistency is wrong and actually average STD dev
